Add PR templates
octokit/webhooks.net pull request #166
Opened 2022-11-11 16:08 UTC by nickfloyd

This PR adds our standardized PR templates.

2022-11-11 16:13 UTC, JamieMagee requested changes
We need to remove the existing PR template in this repo too

2022-11-14 20:56 UTC, nickfloyd commented
> We need to remove the existing PR template in this repo too

On it... thanks for the heads up @JamieMagee ❤️

2022-11-14 21:16 UTC, kfcampbell approved these changes

2022-11-14 22:16 UTC, JamieMagee approved these changes

2022-11-14 22:16 UTC, merged