Add missing "waiting" enum to WorkflowJobStatus.cs
octokit/webhooks.net pull request #364
Opened 2023-10-09 08:48 UTC by rasmus

The `WorkflowJobStatus` enum is lacking the `Waiting`, which cases an exception.

```
[Parameter(Value = "waiting")]
Waiting,
```

```
System.AggregateException: An error occurred while writing to logger(s). (Value 'waiting' is not a valid 'WorkflowJobStatus' enum value.)  ---> System.ArgumentException: Value 'waiting' is not a valid 'WorkflowJobStatus' enum value.   
   at Octokit.Webhooks.Extensions.StringEnum`1.ParseValue()   
   at Octokit.Webhooks.Extensions.StringEnum`1.get_Value()   
   at Octokit.Webhooks.Extensions.StringEnum`1.PrintMembers(StringBuilder builder)   
   at Octokit.Webhooks.Extensions.StringEnum`1.ToString()   
   at Octokit.Webhooks.Models.WorkflowJobEvent.WorkflowJob.PrintMembers(StringBuilder builder)   
   at Octokit.Webhooks.Models.WorkflowJobEvent.WorkflowJob.ToString()   
   at Octokit.Webhooks.Events.WorkflowJobEvent.PrintMembers(StringBuilder builder)   
   at Octokit.Webhooks.Events.WorkflowJob.WorkflowJobWaitingEvent.PrintMembers(StringBuilder builder)   
   at Octokit.Webhooks.Events.WorkflowJob.WorkflowJobWaitingEvent.ToString()   
   at Microsoft.Extensions.Logging.Console.JsonConsoleFormatter.WriteItem(Utf8JsonWriter writer, KeyValuePair`2 item)   
   at Microsoft.Extensions.Logging.Console.JsonConsoleFormatter.<WriteScopeInformation>b__4_0(Object scope, Utf8JsonWriter state)   
   at Microsoft.Extensions.Logging.LoggerFactoryScopeProvider.ForEachScope[TState](Action`2 callback, TState state)   
   at Microsoft.Extensions.Logging.Console.JsonConsoleFormatter.WriteScopeInformation(Utf8JsonWriter writer, IExternalScopeProvider scopeProvider)   
   at Microsoft.Extensions.Logging.Console.JsonConsoleFormatter.Write[TState](LogEntry`1& logEntry, IExternalScopeProvider scopeProvider, TextWriter textWriter)   
   at Microsoft.Extensions.Logging.Console.ConsoleLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)   
   at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|12_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, TState& state)    
   --- End of inner exception stack trace ---   
   at Microsoft.Extensions.Logging.Logger.ThrowLoggingError(List`1 exceptions)   
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)   
   at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)   
   at Microsoft.Extensionsging.LoggerExtensions.Log.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)   
 [...]
```
----

### Before the change?

* Exception being thrown due to unknown enum value

### After the change?

* No exception

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes
- [ ] No

----

2023-10-09 08:55 UTC, JamieMagee approved these changes

2023-10-09 08:57 UTC, JamieMagee commented
Thanks for the contribution!

Can I ask what was the cause of the exception? StringEnum was supposed to prevent this type of exception.

I'm limited in the amount of debugging I can do right now as I'm traveling the next couple of days and only have mobile access.

2023-10-09 11:41 UTC, rasmus commented
Just had a (very quick) read through the `StringEnum` and it seems to throw an exception if the value isn't define

2023-10-10 20:49 UTC, nickfloyd commented
Hey @rasmus,

For clarity the file you were looking to changed is [WorkflowJobStatus](https://github.com/octokit/webhooks.net/pull/364/files#diff-71fa8ccf15625e320a5740fadd84573569060d671eaea06b47dc00dbdf867be5)

According to the schema  status' for `workflow jobs` are limited to:
```
"status": {
  "description": "The phase of the lifecycle that the job is currently in.",
  "type": "string",
  "enum": [
    "queued",
    "in_progress",
    "completed"
  ],
  "examples": [
    "queued"
 ]
},
```

[Workflow runs](https://github.com/octokit/webhooks.net/blob/main/src/Octokit.Webhooks/Models/WorkflowRunStatus.cs) on the other hand have a much more broad set of status' - they can be viewed in the docs [here](https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#list-workflow-runs-for-a-repository).

I can totally see where this can be confusing so I wanted to clarity which one (`Workflow Jobs` or `Workflow Runs`) were you wanting to work with?

2023-10-11 07:01 UTC, rasmus commented
I admit, this PR was created while we were doing a hectic debug session on our own bug and this popped up in the logs.

The initial commit was a copy-paste from the `WorkflowJobStatus`, so I thought it was a mistake in this project as its in the other and we saw the exception in our logs.
https://github.com/octokit/octokit.net/blob/main/Octokit/Models/Response/WorkflowJobStatus.cs#L13-L14

2023-10-12 20:30 UTC, nickfloyd commented
@rasmus Got it!  Thank you for the clarification!  As expected, you are correct.  It seems that our documents are incorrect (as well as our OpenAPI schema).  Something similar has been [reported](https://github.com/github/rest-api-description/issues/1634) by other users as well and also [fixed](https://github.com/octokit/octokit.net/pull/2732) in Octokit.net.

Once we get CI green, we'll work to get this in.  I'll also be creating a ticket to address the inaccuracy in the OpenAPI definition.  Apologies for all of the trouble.

2023-10-12 20:37 UTC, nickfloyd requested changes

2023-10-12 20:37 UTC, nickfloyd commented on src/Octokit.Webhooks/Models/WorkflowJobEvent/WorkflowJobStatus.cs
> +    Waiting,
```suggestion
    Waiting,
```

2023-10-12 21:12 UTC, JamieMagee commented
> Just had a (very quick) read through the `StringEnum` and it seems to throw an exception if the value isn't define

You can guard against this by using the `TryParse` method on `StringEnum`. See [the documentation][1] for more info.

[1]: https://octokitnet.readthedocs.io/en/latest/working-with-enums/

2023-10-12 21:14 UTC, JamieMagee approved these changes

2023-10-12 21:16 UTC, nickfloyd approved these changes

2023-10-12 21:16 UTC, merged

2023-10-12 21:28 UTC, nickfloyd commented
@rasmus Just a quick follow up.  I submitted a PR to get this updated in the GitHub OpenAPI definitions. Hopefully that will get published and into docs once it has been merged.